server:
  port: 8084

spring:
  application:
    name: search-service
  elasticsearch:
    uris: ${ELASTIC_SEARCH_URI:}
    username: ${ELASTIC_SEARCH_USERNAME:}
    password: ${ELASTIC_SEARCH_PASSWORD:}
